# Generated by Django 4.2 on 2024-02-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"app_label": "courses"},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Оплаченный продукт",
            ),
        ),
    ]
