# Generated by Django 4.2 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lesson_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/previews",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lessons/previews",
                verbose_name="Превью",
            ),
        ),
    ]
